### ISSUE TITLE
The problem of getting Chinese Tibetan parallel corpus

### ISSUE THREAD

**Issue by CrystalWLH** [Esukhia/Corpora#2]
Hi,
I am doing research on Tibetan-Chinese machine translation. But it is a pity that I haven't big-scale Chinese-Tibetan parallel corpus. So I want to asking for help, and  hope someone can tell me how to get Tibetan-Chinese parallel data.

**Comment by ngawangtrinley** [comment]
Hi there, what kind of parallel data are you looking for? We have some parallel data of buddhist texts, but nothing for modern language.

![image](https://user-images.githubusercontent.com/17675331/49376201-7143be00-f741-11e8-9463-95ef8cd1bf8e.png)

**Comment by CrystalWLH** [comment]
Oh, Thanks for your reply.  I want to use parallel corpus to implement Tibetan-Chinese machine translation. To be honest, I am not sure if parallel data of buddhist texts match the task. But if you are willing to share the data with me, I would like to thank you very much.
